language: node_js
node_js:
  - 10
deploy:
  provider: pages
  cleanup: true
  token: GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: develop
  project_name: SuperTable
cache: yarn
install: true
script: echo "npm test temporarily disabled"
env:
  global:
    - CAMPFIRE_TOKEN=abc123
      - TIMEOUT=1000