language: node_js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 5352f5e7392573d2ec202609f6b9f581380683bf  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: develop
  project_name: SuperTable